name: Lint title

on: pull_request

jobs:
  lint-pr-title:
    name: Lint title
    runs-on: ubuntu-latest
    steps:
      - name: Lint title
        uses: amannn/action-semantic-pull-request@v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}